import type { Dict } from "./dictionary";

export const en: Dict = {
  meta: {
    title: "Monarch — your intelligence on your own hardware",
    description:
      "Monarch is a local AI for Windows. Chat, code and tasks right on your computer: the plan is shown up front, important actions need your permission, and results are verified.",
  },
  chrome: {
    skip: "Skip to content",
    home: "Monarch — home",
    nav: [
      { href: "how-it-works", label: "How it works" },
      { href: "security", label: "Security" },
      { href: "principles", label: "Principles" },
      { href: "updates", label: "Versions" },
      { href: "documentation", label: "Docs" },
    ],
    download: "Download",
    menu: "Menu",
    close: "Close",
    language: "Language",
    pendingTranslation: "translation in progress",
  },
  hero: {
    kicker: "Monarch 0.2.5 · Windows 10 and 11",
    title: [
      [{ t: "Your " }, { t: "intelligence", accent: true }, { t: " —" }],
      [{ t: "on your own " }, { t: "hardware", accent: true }, { t: "." }],
    ],
    lede: "A local AI for Windows: chat, code and tasks on your own computer. Monarch shows its plan, asks before important actions and verifies the result.",
    primary: "Download for Windows",
    secondary: "How Monarch works",
    facts: [
      { value: "Local", label: "models and data stay on your device", claim: "localFirst" },
      { value: "On request", label: "internet and cloud only with consent", claim: "consentEgress" },
      { value: "Verified", label: "results are checked separately", claim: "resultVerified" },
    ],
    scrollCue: "Scroll — let’s look inside",
    crestLabel: "The Monarch crest: a shield with a crown and circuit traces",
  },
  hardware: {
    index: "01",
    kicker: "On your hardware",
    title: "All the thinking happens here — inside your computer.",
    lede: "Monarch’s models run on your PC’s processor and memory. Chats, files and history live on your drive, not on someone else’s server.",
    labels: {
      cpu: "Processor",
      ram: "Memory",
      ssd: "Drive",
      ssdNote: "chats · files · history",
      net: "Network",
      netNote: "only with consent",
      model: "Model",
    },
    picker: {
      label: "How much memory does your computer have?",
      unit: "GB",
      fits: "Fits",
      tight: "Not enough memory",
      hint: "On first launch Monarch suggests a model that suits your computer. You can add more later in settings.",
      models: [
        { name: "Basic 2B", note: "Fast · basic", ram: 8, beta: false },
        { name: "Basic 12B", note: "Fast · smarter", ram: 16, beta: false },
        { name: "Pro 27B", note: "Slow · maximum", ram: 30, beta: true },
      ],
      options: [8, 16, 32, 64],
    },
    notes: [
      {
        title: "Models ship separately",
        text: "The installer doesn’t carry gigabytes of weights. You pick a model on first launch — or skip it and install one later.",
      },
      {
        title: "Internet only when needed",
        text: "On its own, Monarch goes online only to check for updates. Search and cloud services run only after you agree.",
      },
      {
        title: "Honest about speed",
        text: "Response speed depends on the model and your hardware. The bigger the model, the smarter — and the slower — it is.",
      },
    ],
  },
  journey: {
    index: "02",
    kicker: "The path of a request",
    title: "Words are not results. Monarch checks the deed.",
    lede: "Every task takes the same path. The model proposes — it doesn’t decide.",
    choose: "Pick a request",
    stations: [
      { id: "ask", title: "Request", text: "You write in plain words." },
      { id: "oscar", title: "Oscar understands", text: "Tells a command apart from pasted text, logs and code." },
      { id: "action", title: "Exact action", text: "The task becomes a concrete action with parameters." },
      { id: "policy", title: "Permission check", text: "A separate layer decides: allow, ask you, or deny." },
      { id: "kernel", title: "Execution", text: "The Kernel does exactly what was approved." },
      { id: "verify", title: "Verification", text: "Monarch looks at what actually changed." },
      { id: "receipt", title: "Receipt", text: "A result with proof, not a nice sentence." },
    ],
    lanes: { allow: "Allow", confirm: "Ask you", deny: "Deny" },
    scenarios: [
      {
        id: "open",
        prompt: "Open Notepad",
        action: "Open the “Notepad” app",
        verdict: "allow",
        verdictText: "Within the access mode you chose",
        check: "The Notepad window appeared",
        receipt: "Done · window opened and found",
      },
      {
        id: "search",
        prompt: "Find the latest Rust news",
        action: "Web search: “Rust news”",
        verdict: "confirm",
        verdictText: "Needs the internet — Monarch asks once",
        check: "Sources fetched and read",
        receipt: "Done · summary with source links",
      },
      {
        id: "wipe",
        prompt: "Delete everything on drive C:",
        action: "Delete the root of drive C:\\",
        verdict: "deny",
        verdictText: "Hard stop — no confirmation can lift it",
        check: "Nothing was executed",
        receipt: "Denied · drive root is protected",
      },
    ],
    oscarStates: {
      ask: "listening",
      oscar: "thinking",
      action: "coding",
      policy: "security",
      kernel: "coding",
      verify: "thinking",
      receipt: "success",
      deny: "error",
    },
    receiptLabel: "Receipt",
    hardLimitsTitle: "What no “yes” can unlock",
    hardLimits: [
      "Deleting a drive root or an entire workspace",
      "Changing protected areas of Windows",
      "Escaping the allowed folder through links and workarounds",
      "Access to the Safe, passwords, tokens and keys",
      "Disabling Monarch’s or Windows’ protections",
    ],
  },
  safe: {
    index: "03",
    kicker: "Monarch Safe",
    title: "A vault even Oscar can’t enter.",
    lede: "Encrypted storage for files and private chats. A separate process with no network, its own PIN and its own keys.",
    points: [
      { value: "AES-256-GCM", text: "Every file version gets its own random 256-bit key." },
      { value: "PIN + device", text: "The PIN is bound to a secret on this computer: a copy of the vault on another PC can’t check it." },
      { value: "3 keys", text: "Three recovery keys in case you forget the PIN. Three wrong PINs destroy the keys." },
      { value: "No network", text: "The Safe window is isolated: no network, no launching programs, clipboard closed by default." },
    ],
    wall: "The agent never gets access to the Safe. Not with full access, not with owner rights.",
    limit: "An honest boundary: the Safe can’t protect you from malware already running under your account while it’s unlocked.",
    labels: { file: "report.pdf", vault: "Safe", blocked: "No access", pin: "PIN" },
  },
  guard: {
    index: "04",
    kicker: "Monarch Security",
    title: "A sentinel that stays when the window closes.",
    lede: "Security runs apart from the app: close Monarch and the watch goes on. It’s built on strict rule-based checks; a model only advises.",
    modesLabel: "Agent action protection mode",
    modes: [
      { id: "off", label: "Off", text: "Agent action protection is off. Turning it off requires confirmation and a PIN." },
      { id: "observe", label: "Observe", text: "Notices suspicious actions and logs them without getting in the way." },
      { id: "guard", label: "Guard", text: "Stops a risky agent action before it runs." },
      { id: "strict", label: "Strict", text: "Every sensitive action waits for your confirmation." },
    ],
    facts: [
      "Scans never delete files or kill processes on their own",
      "Online file reputation checks are off by default",
      "The log keeps codes and hashes, not the contents of your files",
    ],
    labels: { app: "Monarch", closed: "Window closed", sentinel: "Security", running: "Still running", events: "Events" },
    honest: "Security is an early version (Preview), not an antivirus. It complements Windows Defender rather than replacing it.",
  },
  max: {
    index: "05",
    kicker: "MAX · in development, version 0.3",
    title: "The cloud — only when you call it.",
    lede: "MAX turns on powerful cloud models with a single switch. Every service is connected separately, with its own consent.",
    consentTitle: "Three-part consent",
    consent: ["The chosen service’s terms and privacy", "What data will go to the cloud", "Possible charges from the provider"],
    ready: "Connected: the request goes only to the chosen service",
    waiting: "Tick all three — until then MAX sends not a single byte",
    points: [
      "Each service key is encrypted separately and never reaches child processes",
      "No silent switching to another service or model",
      "No automatic paid retries",
    ],
    providersLabel: "12 services to choose from",
    local: "Your computer",
    cloud: "Chosen service",
  },
  facts: {
    index: "06",
    kicker: "Facts",
    title: "Monarch in numbers.",
    lede: "Figures come from the open source code of Monarch 0.2.5 and its public releases.",
    items: {
      files: "files in the open source code",
      tests: "test files",
      modules: "modules in one system",
      releases: "installers published",
      processes: "separate processes: window, module runtime, Oscar, Safe and Security",
      trackers: "trackers or third-party analytics in the app",
    },
    languagesTitle: "What Monarch is made of",
    source: "Source: github.com/MrPastio/monarch, snapshot of 25 September 2026",
    timelineTitle: "How Monarch grew",
    timeline: [
      { date: "12 June 2026", title: "Open source", text: "Monarch appears on GitHub." },
      { date: "0.2.0", title: "Beta and Studio", text: "The first public Beta." },
      { date: "0.2.2", title: "Monarch Safe", text: "An encrypted vault for files and chats." },
      { date: "22 July 2026", title: "Updates inside Monarch", text: "A signed stable channel and one-click install." },
      { date: "0.2.4", title: "Agent Runtime", text: "Oscar performs real, verified actions." },
      { date: "25 August 2026", title: "0.2.5 · Agent-First", text: "Computer Use, new models, Memory V4." },
      { date: "Now", title: "0.3 · Astra V3 and MAX", text: "In development — not published yet." },
    ],
  },
  download: {
    index: "07",
    kicker: "Download",
    title: "Take Monarch home.",
    lede: "Free, no account. One installer for Windows; models are picked on first launch.",
    primary: "Download Monarch",
    all: "All versions",
    requirements: [
      { label: "System", value: "Windows 10 or 11, 64-bit" },
      { label: "Memory", value: "8 GB minimum, 16 GB recommended" },
      { label: "Rights", value: "installs without administrator rights" },
    ],
    file: "File",
    size: "Size",
    date: "Released",
    sha: "SHA-256",
    signature: "Channel signature",
    copy: "Copy",
    copied: "Copied",
    smartscreen: "The installer doesn’t have an Authenticode certificate yet, so Windows SmartScreen may warn you on launch. Check the SHA-256 — it matches the signed manifest.",
    edge: "If Microsoft Edge blocks the download, use another browser or the GitHub Release page.",
    unavailable: "We couldn’t verify the release right now. You can download it from the GitHub Release page.",
    github: "GitHub Release",
  },
  faq: {
    title: "The short version",
    items: [
      {
        q: "Does Monarch work without the internet?",
        a: "Yes — the main work, from chat and code to tasks and models, happens on your computer. The internet is needed to check for updates, and for search and cloud services that only turn on with your consent.",
      },
      {
        q: "Can Monarch do something without asking?",
        a: "Only what the access mode you chose allows. Sensitive actions need a separate confirmation, and dangerous ones — like deleting a drive root or touching the Safe — are forbidden outright.",
      },
      {
        q: "Why does Windows warn me during installation?",
        a: "The installer doesn’t have an Authenticode certificate yet, so it has no SmartScreen “reputation”. The update channel is signed with Ed25519, and you can verify the file itself by its SHA-256.",
      },
      {
        q: "How much does Monarch cost?",
        a: "Monarch is free. You would only ever pay cloud providers — and only if you connect them in MAX yourself.",
      },
      {
        q: "What happens to my data when I update?",
        a: "Chats, settings, models and the Safe are kept. The update is installed next to the old version and rolls back if the new one fails to start.",
      },
    ],
  },
  footer: {
    tagline: "Your intelligence — on your own hardware.",
    columns: [
      {
        title: "Product",
        links: [
          { href: "how-it-works", label: "How it works" },
          { href: "security", label: "Security" },
          { href: "principles", label: "Principles" },
        ],
      },
      {
        title: "Download",
        links: [
          { href: "download", label: "Download" },
          { href: "updates", label: "All versions" },
          { href: "documentation", label: "Docs" },
        ],
      },
    ],
    external: [
      { href: "https://github.com/MrPastio/monarch", label: "Source code" },
      { href: "https://github.com/MrPastio/monarch-releases/releases", label: "GitHub Releases" },
    ],
    honesty:
      "The update manifest is signed with Ed25519 and the installer is verified by SHA-256. The installer doesn’t have an Authenticode certificate yet, so Windows SmartScreen may show a warning.",
    rights: "Monarch · MrPastio",
  },
  ui: {
    oscar: "Oscar",
    consentAsk: "Allow a one-time web search?",
    consentYes: "Allow",
    parseVerb: "command",
    parseObject: "target",
    actionKeys: ["action", "source", "model"],
    actionSource: "desktop · your request",
    actionModel: "proposes, doesn’t execute",
    kernelSteps: ["Check approval", "Execute", "Record the event"],
    receiptKeys: ["Request", "Action", "Decision", "Check"],
    agent: "agent",
    events: [
      { time: "02:14", text: "Startup items: no changes", tone: "ok" },
      { time: "02:16", text: "New file in Downloads checked", tone: "ok" },
      { time: "02:21", text: "Network connection: known process", tone: "ok" },
      { time: "02:30", text: "Attempt to change a scheduled task", tone: "warn" },
    ],
    back: "Back",
    next: "Next",
    notFoundTitle: "This page doesn’t exist.",
    notFoundText: "The address may have changed. Go home or open the list of versions.",
    toHome: "Home",
  },
  pages: {
    download: {
      title: "Download Monarch",
      lede: "The current version, how to verify the file, and a full archive of every release.",
      verifyTitle: "How to verify the file",
      verifySteps: [
        { title: "Download the installer", text: "With the button above or from the GitHub Release page — it’s the same file." },
        { title: "Compute SHA-256", text: "Open PowerShell in your Downloads folder and run:" },
        { title: "Compare", text: "The result must match the SHA-256 on this page character for character. If it doesn’t, don’t run the file." },
      ],
      command: "Get-FileHash .\\Monarch-Setup-0.2.5.0.exe -Algorithm SHA256",
      archiveTitle: "Version archive",
      archiveLede: "Every published installer. For everyday use we recommend the latest: older versions don’t receive fixes.",
      stateCurrent: "Current",
      stateArchive: "Archive",
      stateRevoked: "Revoked",
      stateHistory: "No installer",
      oldWarning: "This version doesn’t receive fixes. Unless you have a specific reason, download the current one.",
      revokedWarning: "This version was revoked from the update channel. It shouldn’t be installed for real work.",
      revokedAck: "I understand the risk and want to download a revoked version",
      historyNote: "This version shipped before the public channel — there’s no installer in the archive.",
      download: "Download",
      notes: "What’s new",
      sourceSnapshot: "GitHub is unavailable right now — showing a saved list of releases.",
    },
    updates: {
      title: "Monarch history",
      lede: "Every version — what changed and why. From the first Beta to today. Release notes are written in Russian.",
      future: {
        label: "In progress",
        title: "0.3 · Astra V3 and MAX",
        text: "A new agent core built on typed capabilities, the MAX cloud mode with 12 services, Gmail, GitHub and Calendar integrations. Not published yet.",
      },
      categories: { features: "Features", fixes: "Fixes", security: "Security", studio: "Studio" },
      open: "Details",
      published: "Published",
      withdrawnTitle: "Why it was revoked",
      supersededBy: "Replaced by",
      whatChanged: "What changed",
      howItWorks: "How to update",
      audience: "Who it matters to",
      allVersions: "All versions",
    },
    how: {
      kicker: "How it works",
      title: "How Monarch is built",
      lede: "Several separate processes, one rule-based core and dozens of modules. All of it on your computer.",
      processTitle: "Five processes, each with its own job",
      processes: [
        { id: "window", title: "Monarch window", text: "The Electron interface. This is where you write, choose modes and confirm actions." },
        { id: "runtime", title: "Module runtime", text: "The Kernel and the modules. It listens only on 127.0.0.1 — nothing outside can reach it." },
        { id: "oscar", title: "Oscar", text: "The local backend: models, chat and the agent. Models run on llama.cpp in GGUF format." },
        { id: "safe", title: "Safe", text: "A separate process with no network. Nobody else ever sees the Safe’s keys." },
        { id: "security", title: "Security", text: "A Windows task with limited rights. It keeps working even when Monarch is closed." },
      ],
      kernelTitle: "One decision per action",
      kernelText: "Modules don’t grant themselves rights. They collect facts, and a single layer — the PolicyKernel — makes the final call: allow, ask you, or deny. Verification is separate: an action only counts as done once the core has confirmed its effect.",
      modulesTitle: "23 modules in one system",
      modules: [
        { id: "oscar", name: "Oscar", text: "Chat and an agent that understands the task" },
        { id: "models", name: "Models", text: "Local models and their installation" },
        { id: "memory", name: "Memory", text: "Memory V4: remembers what matters, keeps projects apart" },
        { id: "coder", name: "Coder", text: "Working with code inside a chosen project" },
        { id: "computer", name: "Computer Use", text: "Sees windows, clicks, types — Beta" },
        { id: "system-shell", name: "Terminal", text: "Commands only within your permissions" },
        { id: "knowledge", name: "Knowledge", text: "Search across your documents" },
        { id: "workspace", name: "Workspaces", text: "The boundaries the agent works within" },
        { id: "artifacts", name: "Artifacts", text: "Files and reports Monarch created" },
        { id: "astra", name: "Skills", text: "Ready-made scenarios via “+” or “$”" },
        { id: "voice", name: "Voice", text: "Dictation and speech on the device" },
        { id: "profile", name: "Profile", text: "Personality and conversation style" },
        { id: "safe", name: "Safe", text: "Encrypted storage" },
        { id: "security", name: "Security", text: "Monitoring and action protection" },
        { id: "studio", name: "Studio", text: "Photos and basic video — Alpha" },
        { id: "sharing", name: "Sharing", text: "Local access for your own programs" },
        { id: "telegram", name: "Telegram", text: "A bot for talking to Monarch" },
        { id: "plugins", name: "Plugins", text: "Connectable services" },
        { id: "custom-tools", name: "Custom tools", text: "Tools you add yourself" },
        { id: "device", name: "Device", text: "Hardware details for choosing a model" },
        { id: "diagnostics", name: "Diagnostics", text: "Clear reasons for failures" },
        { id: "assistant", name: "Assistant", text: "Basic answers and routing" },
        { id: "monarch-modules", name: "Registry", text: "The catalog and contract of all modules" },
      ],
      modelsTitle: "Models to choose from",
      modelsText: "Monarch offers Basic 2B, Basic 12B and Pro 27B and recommends the one that fits your computer. Models are downloaded separately from the app and stored on your drive.",
      memoryTitle: "Memory that doesn’t gossip",
      memoryText: "Memory V4 keeps ordinary chats apart from Coder projects, finds what’s useful from past conversations and marks answers where it used memory. You can turn it off; Incognito and sensitive sections never enter it.",
    },
    security: {
      kicker: "Security",
      title: "Trust you can verify",
      lede: "How Monarch decides what it may do, where the hard boundaries are, and what lies beyond them.",
      profilesTitle: "Access modes",
      profiles: [
        { name: "Guided", text: "Monarch proposes steps, and you confirm what matters." },
        { name: "Workspace", text: "Freedom inside the chosen project; outside it — only with permission." },
        { name: "Full local", text: "More independence on your computer. Hard stops still apply." },
      ],
      verdictTitle: "Three possible decisions",
      verdicts: [
        { id: "allow", title: "Allow", text: "The action fits the chosen mode — Monarch executes it and verifies the result." },
        { id: "confirm", title: "Ask you", text: "A one-time confirmation bound to that exact action. If the action changes, a new one is needed." },
        { id: "deny", title: "Deny", text: "A hard stop. Neither confirmation nor owner rights can lift it." },
      ],
      updatesTitle: "Honest updates",
      updatesText: "The stable channel is signed with an Ed25519 key. Monarch checks the signature, size and SHA-256 of the installer before installing, puts the new version next to the old one and rolls back if it fails to start.",
      limitsTitle: "What lies beyond protection",
      limits: [
        "Malware already running under your account",
        "An administrator or a Windows kernel-level compromise",
        "A modified and rebuilt copy of Monarch",
        "Physical recovery of data from an SSD after deletion",
      ],
    },
    principles: {
      kicker: "Principles",
      title: "How Monarch is made",
      lede: "The rules Monarch is designed, written and tested by. They’re the same for people and for the AI agents that help build it.",
      designTitle: "Design",
      design: [
        { title: "Calm glass", text: "A minimal language: black, white, orange and yellow, moderate blur, nothing for effect’s sake." },
        { title: "Motion has weight", text: "Elements arrive and leave from a clear place, unfold and fold. No blinking, no constant glow." },
        { title: "One animation owner", text: "Any transition can be interrupted at any moment and never queues — the interface never makes you wait." },
        { title: "Respect for your settings", text: "If “reduce motion” is on in your system, Monarch and this site show final states without animation." },
      ],
      qualityTitle: "Quality",
      quality: [
        { title: "Compiling isn’t fixing", text: "A task is done when type checks, tests and a real scenario pass — not when the code builds." },
        { title: "Verify the result", text: "In the product and in development alike: an action isn’t done until its effect is confirmed." },
        { title: "Truth in the copy", text: "Every claim on this site is tied to code or a release. A test stops the site from promising “100%” or calling the installer signed while it isn’t." },
        { title: "Honest statuses", text: "Beta, Preview and Alpha are marked right in the interface. Unfinished work is never passed off as finished." },
      ],
      agentsTitle: "Built with AI agents",
      agentsText: "Monarch is developed together with several AI agents. Each has its own role and admission under an open policy: Codex and Claude as lead developers, Grok admitted as a worker, unknown agents not admitted. Each task is bound to a code version, allowed paths and a deadline; accepting the result is never automatic.",
      agentsSource: "The policy is described in SECURITY.md of the open repository",
      brandTitle: "The mark",
      brandText: "A shield with a crown and circuit traces: protection, sovereignty and computing on your own hardware. The primary version sits on a dark ground, the second on a light one.",
      brandDark: "Primary · dark ground",
      brandLight: "Secondary · light ground",
    },
    docs: {
      kicker: "Docs",
      title: "Getting started",
      lede: "Installation, first launch and answers to common questions — in plain words.",
      sections: [
        {
          id: "install",
          title: "Installation",
          steps: [
            "Download Monarch-Setup from this site or from GitHub Release.",
            "Run the installer. No administrator rights needed — Monarch installs for your account.",
            "If SmartScreen shows a warning, click “More info” → “Run anyway”. Check the SHA-256 first.",
          ],
        },
        {
          id: "first-run",
          title: "First launch",
          steps: [
            "Monarch suggests a model for your computer. You can pick several or skip the download.",
            "The download shows real progress and resumes after a restart.",
            "If automatic model installation fails, the window has step-by-step instructions with the exact files.",
          ],
        },
        {
          id: "permissions",
          title: "Permissions",
          steps: [
            "Choose an access mode in settings: from guided to full local.",
            "Web search and cloud services ask for consent separately.",
            "Dangerous actions are always forbidden — that isn’t a setting.",
          ],
        },
        {
          id: "updates",
          title: "Updates",
          steps: [
            "Monarch checks the signed stable channel itself and offers a one-click update.",
            "Chats, settings, models and the Safe are kept.",
            "If the new version fails to start, Monarch returns to the previous one.",
          ],
        },
      ],
      troubleTitle: "If something goes wrong",
      trouble: [
        { q: "Edge blocks the download", a: "Use another browser or the GitHub Release page. Check the SHA-256 after downloading." },
        { q: "Answers are slow", a: "Pick a smaller model in settings. Pro 27B is noticeably slower than the Basic models and needs about 30 GB of memory." },
        { q: "Not enough disk space", a: "Models take gigabytes. You can remove them, or download them later in settings." },
      ],
    },
  },
};
