import type { Dict } from "./dictionary";

export const en: Dict = {
  meta: {
    title: "Monarch — your intelligence on your own hardware",
    description:
      "Monarch is a local AI for Windows. Chat, code and tasks right on your computer: the plan is shown up front, important actions need your permission, and results are verified.",
  },
  chrome: {
    skip: "Skip to content",
    home: "Monarch — home",
    nav: [
      { href: "how-it-works", label: "How it works" },
      { href: "security", label: "Security" },
      { href: "principles", label: "Principles" },
      { href: "updates", label: "Versions" },
      { href: "documentation", label: "Docs" },
    ],
    download: "Download",
    menu: "Menu",
    close: "Close",
    language: "Language",
    pendingTranslation: "translation in progress",
  },
  hero: {
    kicker: "Monarch 0.2.5 · Windows 10 and 11",
    title: [
      [{ t: "Your " }, { t: "intelligence", accent: true }, { t: " —" }],
      [{ t: "on your own " }, { t: "hardware", accent: true }, { t: "." }],
    ],
    lede: "A local AI for Windows: chat, code and tasks on your own computer. Monarch shows its plan, asks before important actions and verifies the result.",
    primary: "Download for Windows",
    secondary: "How Monarch works",
    facts: [
      { value: "Local", label: "models and data stay on your device", claim: "localFirst" },
      { value: "On request", label: "internet and cloud only with consent", claim: "consentEgress" },
      { value: "Verified", label: "results are checked separately", claim: "resultVerified" },
    ],
    crestLabel: "The Monarch crest: a shield with a crown and circuit traces",
    note: "Free, no account needed. Models run right on your computer.",
    badge: "What’s new",
    free: "free",
    after: {
      title: "Your download has started",
      lede: "While the file downloads, here’s what comes next.",
      steps: [
        { title: "Open the installer", text: "Monarch-Setup in your Downloads folder. No administrator rights needed." },
        { title: "If Windows warns you", text: "Click “More info” → “Run anyway”. You can check the SHA-256 first." },
        { title: "Pick a model", text: "Monarch suggests one that suits your computer. You can skip it and add one later." },
      ],
      verify: "How to verify the file",
      close: "Got it",
    },
    platform: {
      other: "Monarch runs on Windows 10 and 11, 64-bit.",
      phone: "Monarch is an app for Windows PCs. Open this page on your computer.",
      copy: "Copy link",
      copied: "Link copied",
    },
    window: {
      label: "Demo: how Oscar carries out a request in Monarch",
      newChat: "New chat",
      recent: "Recent",
      chats: ["Quarterly report", "Backup script", "Trip ideas"],
      safe: "Safe",
      security: "Security running",
      greeting: "What shall we do?",
      placeholder: "Message Oscar…",
      model: "Basic 12B",
      local: "local",
      thinking: "Oscar is working out the task…",
      plan: "Plan",
      allowedOnce: "Allowed once",
      done: "Done: approved, carried out, logged",
      try: "Try a request",
    },
  },
  abilities: {
    index: "01",
    kicker: "What it does",
    title: "One assistant — *all the work* at your computer.",
    lede: "Oscar holds the conversation, writes code in your project, works with windows and remembers what matters. The Beta and Preview labels are the same as in the app.",
    example: "example",
    items: [
      { id: "agent", title: "Long tasks, step by step", text: "Oscar breaks work into clear steps and shows the plan, the current step and the result. You can stop it at any moment.", tag: "", claim: "agentTasks" },
      { id: "computer", title: "Computer Use", text: "Sees open windows, launches apps, clicks, types and scrolls. It checks the window before acting and the result after.", tag: "Beta", claim: "computerUse" },
      { id: "coder", title: "Coder", text: "A separate mode for code: pick a project and Oscar works inside its folder.", tag: "", claim: "coderProjects" },
      { id: "memory", title: "Memory V4", text: "Remembers what matters and keeps ordinary chats apart from projects. It marks answers that used memory; Incognito never gets in.", tag: "", claim: "memoryV4" },
      { id: "voice", title: "Voice", text: "Long dictation and read-aloud with a choice of voice, speed and intonation.", tag: "Beta", claim: "voiceBeta" },
      { id: "skills", title: "Skills and Personality", text: "Ready-made scenarios via “+” or “$”. You can pick a conversation style for a single task.", tag: "Preview", claim: "skillsPreview" },
      { id: "telegram", title: "Telegram", text: "Pair your phone with a one-time code and message Oscar from Telegram. Messages go through Telegram’s servers.", tag: "", claim: "telegramBot" },
      { id: "sharing", title: "Sharing", text: "Local models for your own programs: an OpenAI-style API at 127.0.0.1.", tag: "", claim: "sharingApi" },
    ],
    vignettes: {
      plan: ["Find the quarterly reports", "Put the numbers in a table", "Check the totals", "Show the result"],
      stop: "Stop",
      step: "Step",
      window: "Settings",
      button: "Save",
      folder: "my-project",
      files: ["backup.ps1", "README.md", "notes.txt"],
      memoryChats: "Ordinary chats",
      memoryProject: "Project · website",
      memoryNote: "Remembered: reports go out on Mondays",
      memoryUsed: "memory used",
      voicePreset: "Calm · 1.0×",
      dictation: "Dictation",
      skillsLabel: "Skills",
      skills: ["Short summary", "Translation", "Task plan"],
      tgUser: "Remind me at 6 pm to call mum",
      tgBot: "Done, I’ll remind you at 6 pm.",
      tgCode: "Pairing code · 15 minutes",
    },
  },
  hardware: {
    index: "03",
    kicker: "On your hardware",
    title: "All the thinking happens *here* — inside your computer.",
    lede: "Monarch’s models run on your PC’s processor and memory. Chats, files and history live on your drive, not on someone else’s server.",
    picker: {
      label: "How much memory does your computer have?",
      unit: "GB",
      recommended: "Monarch suggests",
      fits: "Fits",
      tight: "Not enough memory",
      hint: "On first launch Monarch suggests a model that suits your computer. You can add more later in settings.",
      models: [
        { name: "Basic 2B", note: "Fast · basic", ram: 8, beta: false },
        { name: "Basic 12B", note: "Fast · smarter", ram: 16, beta: false },
        { name: "Pro 27B", note: "Slow · maximum", ram: 30, beta: true },
      ],
      options: [8, 16, 32, 64],
    },
    notes: [
      {
        title: "Models ship separately",
        text: "The installer doesn’t carry gigabytes of weights. You pick a model on first launch — or skip it and install one later.",
      },
      {
        title: "Internet only when needed",
        text: "On its own, Monarch goes online only to check for updates. Search and cloud services run only after you agree.",
      },
      {
        title: "Honest about speed",
        text: "Response speed depends on the model and your hardware. The bigger the model, the smarter — and the slower — it is.",
      },
    ],
  },
  journey: {
    index: "02",
    kicker: "The path of a request",
    title: "Words are not results. Monarch *checks the deed*.",
    lede: "Every task takes the same path. The model proposes — it doesn’t decide.",
    choose: "Pick a request",
    stations: [
      { id: "ask", title: "Request", text: "You write in plain words." },
      { id: "oscar", title: "Oscar understands", text: "Tells a command apart from pasted text, logs and code." },
      { id: "action", title: "Exact action", text: "The task becomes a concrete action with parameters." },
      { id: "policy", title: "Permission check", text: "A separate layer decides: allow, ask you, or deny." },
      { id: "kernel", title: "Execution", text: "The Kernel does exactly what was approved." },
      { id: "verify", title: "Verification", text: "Monarch looks at what actually changed." },
      { id: "receipt", title: "Receipt", text: "A result with proof, not a nice sentence." },
    ],
    lanes: { allow: "Allow", confirm: "Ask you", deny: "Deny" },
    scenarios: [
      {
        id: "open",
        prompt: "Open Notepad",
        action: "Open the “Notepad” app",
        verdict: "allow",
        verdictText: "Within the access mode you chose",
        check: "The Notepad window appeared",
        receipt: "Done · window opened and found",
      },
      {
        id: "search",
        prompt: "Find the latest Rust news",
        action: "Web search: “Rust news”",
        verdict: "confirm",
        verdictText: "Needs the internet — Monarch asks once",
        check: "Sources fetched and read",
        receipt: "Done · summary with source links",
      },
      {
        id: "wipe",
        prompt: "Delete everything on drive C:",
        action: "Delete the root of drive C:\\",
        verdict: "deny",
        verdictText: "Hard stop — no confirmation can lift it",
        check: "Nothing was executed",
        receipt: "Denied · drive root is protected",
      },
    ],
    receiptLabel: "Receipt",
    hardLimitsTitle: "What no “yes” can unlock",
    hardLimits: [
      "Deleting a drive root or an entire workspace",
      "Changing protected areas of Windows",
      "Escaping the allowed folder through links and workarounds",
      "Access to the Safe, passwords, tokens and keys",
      "Disabling Monarch’s or Windows’ protections",
    ],
  },
  access: {
    kicker: "Access modes",
    title: "How much freedom Oscar gets — *is up to you*.",
    lede: "Three autonomy modes, as in Monarch’s settings. Hard limits don’t depend on the mode.",
    modesLabel: "Autonomy mode",
    modes: [
      { id: "guided", name: "Always ask", text: "Reads freely. Changes, launching programs and network access need an exact one-time permission." },
      { id: "workspace", name: "On its own in the project", text: "Reads and changes project files by itself. Launching programs, network and deletion stay under control." },
      { id: "device", name: "On its own on the device", text: "Ordinary local actions on its own. It still asks before deleting or controlling the device." },
    ],
    actionsLabel: "What happens to the action",
    actions: [
      { id: "read", text: "Read a file", verdicts: ["allow", "allow", "allow"] },
      { id: "write", text: "Change a file in the project", verdicts: ["confirm", "allow", "allow"] },
      { id: "execute", text: "Launch a program", verdicts: ["confirm", "confirm", "allow"] },
      { id: "delete", text: "Delete a file", verdicts: ["confirm", "confirm", "confirm"] },
      { id: "money", text: "Payment or money transfer", verdicts: ["deny", "deny", "deny"] },
      { id: "system", text: "Change protected areas of Windows", verdicts: ["deny", "deny", "deny"] },
    ],
    note: "An “ask” permission is one-time and tied to one exact action. If the action changes, a new one is needed.",
    claim: "accessModes",
  },
  safe: {
    index: "04",
    kicker: "Monarch Safe",
    title: "A vault *even Oscar* can’t enter.",
    lede: "Encrypted storage for files and private chats. A separate process with no network, its own PIN and its own keys.",
    points: [
      { value: "AES-256-GCM", text: "Every file version gets its own random 256-bit key." },
      { value: "PIN + device", text: "The PIN is bound to a secret on this computer: a copy of the vault on another PC can’t check it." },
      { value: "3 keys", text: "Three recovery keys in case you forget the PIN. Three wrong PINs destroy the keys." },
      { value: "No network", text: "The Safe window is isolated: no network, no launching programs, clipboard closed by default." },
    ],
    wall: "The agent never gets access to the Safe. Not with full access, not with owner rights.",
    limit: "An honest boundary: the Safe can’t protect you from malware already running under your account while it’s unlocked.",
    labels: { file: "report.pdf", vault: "Monarch Safe", locked: "Locked", open: "Open", blocked: "No access", pin: "PIN", sealed: "Encrypted · AES-256-GCM", replay: "Lock again" },
  },
  guard: {
    index: "05",
    kicker: "Monarch Security",
    title: "A sentinel that *stays* when the window closes.",
    lede: "Security runs apart from the app: close Monarch and the watch goes on. It’s built on strict rule-based checks; a model only advises.",
    modesLabel: "How Security responds to Oscar’s actions",
    modes: [
      { id: "off", label: "Off", text: "Only the immutable limits remain. Turning protection off takes a confirmation and a PIN.", threshold: 0 },
      { id: "observe", label: "Observe", text: "Scores the risk and logs it, but doesn’t step in.", threshold: 0 },
      { id: "guard", label: "Guard", text: "Stops an action when its risk score is 70% or higher.", threshold: 70 },
      { id: "strict", label: "Strict", text: "Steps in earlier — from a risk score of 50%.", threshold: 50 },
    ],
    risk: {
      label: "Risk score",
      example: "Scores are illustrative",
      samples: [
        { text: "Read the project folder", score: 12 },
        { text: "Change startup programs", score: 58 },
        { text: "Run a downloaded file", score: 84 },
      ],
      passed: "carried out",
      logged: "logged",
      stopped: "stopped",
      boundary: "hard limits only",
    },
    desktop: {
      close: "Close Monarch",
      reopen: "Open again",
      toast: "Security keeps running",
      later: [
        { time: "02:41", text: "New program in startup — logged", tone: "warn" },
        { time: "02:43", text: "Network connection: known process", tone: "ok" },
      ],
    },
    facts: [
      "Scans never delete files or kill processes on their own",
      "Online file reputation checks are off by default",
      "The log keeps codes and hashes, not the contents of your files",
    ],
    labels: { app: "Monarch", closed: "Window closed", sentinel: "Security", running: "Still running", events: "Events" },
    honest: "Security is an early version (Beta), not an antivirus. It complements Windows Defender rather than replacing it.",
  },
  max: {
    index: "06",
    kicker: "MAX · in development, version 0.3",
    title: "The cloud — only when *you* call it.",
    lede: "MAX turns on powerful cloud models with a single switch. Every service is connected separately, with its own consent.",
    consentTitle: "Three-part consent",
    consent: ["The chosen service’s terms and privacy", "What data will go to the cloud", "Possible charges from the provider"],
    ready: "Connected: the request goes only to the chosen service",
    waiting: "Tick all three — until then MAX sends not a single byte",
    points: [
      "Each service key is encrypted separately and never reaches child processes",
      "No silent switching to another service or model",
      "No automatic paid retries",
    ],
    providersLabel: "12 services to choose from",
    local: "Your computer",
    cloud: "Chosen service",
    via: "over the internet",
    goesTitle: "Goes to the service",
    goes: ["The request you sent in MAX mode", "Documents you attached yourself"],
    staysTitle: "Stays with you",
    stays: ["Keys to other services, and the Safe", "Memory — until you allow it separately", "Everything unrelated to the request"],
  },
  facts: {
    index: "07",
    kicker: "Facts",
    title: "Monarch *in numbers*.",
    lede: "Figures come from the open source code of Monarch and its public releases.",
    items: {
      files: "files in the open source code",
      tests: "test files",
      modules: "modules in one system",
      releases: "installers published",
      processes: "separate processes: window, module runtime, Oscar, Safe and Security",
      trackers: "trackers or third-party analytics in the app",
    },
    languagesTitle: "What Monarch is made of",
    source: "Source: github.com/MrPastio/monarch, snapshot of 25 September 2026",
    timelineTitle: "How Monarch grew",
    timeline: [
      { date: "12 June 2026", title: "Open source", text: "Monarch appears on GitHub." },
      { date: "0.2.0", title: "First Beta", text: "The first public Beta." },
      { date: "0.2.2", title: "Monarch Safe", text: "An encrypted vault for files and chats." },
      { date: "22 July 2026", title: "Updates inside Monarch", text: "A signed stable channel and one-click install." },
      { date: "0.2.4", title: "Agent Runtime", text: "Oscar performs real, verified actions." },
      { date: "25 August 2026", title: "0.2.5 · Agent-First", text: "Computer Use, new models, Memory V4." },
      { date: "Now", title: "0.3 · Astra V3 and MAX", text: "In development — not published yet." },
    ],
  },
  download: {
    index: "08",
    kicker: "Download",
    title: "Take Monarch *home*.",
    lede: "Free, no account. One installer for Windows; models are picked on first launch.",
    nextTitle: "What happens after the download",
    primary: "Download Monarch",
    all: "All versions",
    requirements: [
      { label: "System", value: "Windows 10 or 11, 64-bit" },
      { label: "Memory", value: "8 GB minimum, 16 GB recommended" },
      { label: "Rights", value: "installs without administrator rights" },
    ],
    file: "File",
    size: "Size",
    date: "Released",
    sha: "SHA-256",
    signature: "Channel signature",
    copy: "Copy",
    copied: "Copied",
    smartscreen: "The installer doesn’t have an Authenticode certificate yet, so Windows SmartScreen may warn you on launch. Check the SHA-256 — it matches the signed manifest.",
    edge: "If Microsoft Edge blocks the download, use another browser or the GitHub Release page.",
    unavailable: "We couldn’t verify the release right now. You can download it from the GitHub Release page.",
    github: "GitHub Release",
  },
  faq: {
    title: "The short version",
    items: [
      {
        q: "Does Monarch work without the internet?",
        a: "Yes — the main work, from chat and code to tasks and models, happens on your computer. The internet is needed to check for updates, and for search and cloud services that only turn on with your consent.",
      },
      {
        q: "Can Monarch do something without asking?",
        a: "Only what the access mode you chose allows. Sensitive actions need a separate confirmation, and dangerous ones — like deleting a drive root or touching the Safe — are forbidden outright.",
      },
      {
        q: "Why does Windows warn me during installation?",
        a: "The installer doesn’t have an Authenticode certificate yet, so it has no SmartScreen “reputation”. The update channel is signed with Ed25519, and you can verify the file itself by its SHA-256.",
      },
      {
        q: "How much does Monarch cost?",
        a: "Monarch is free. The only thing you may ever pay for is a cloud service — and only if you connect it yourself in MAX, which is being prepared for version 0.3.",
      },
      {
        q: "Where are my chats and files stored?",
        a: "On your drive. Models, chats and files stay on your computer. Something leaves only if you turn on search or a cloud service yourself.",
      },
      {
        q: "Can I stop Oscar in the middle of a task?",
        a: "Yes. The plan and the current step are visible right in the chat, and you can stop a task at any moment — including window control in Computer Use.",
      },
      {
        q: "Do I need an account?",
        a: "No. Monarch downloads and works without signing up.",
      },
      {
        q: "What happens to my data when I update?",
        a: "Chats, settings, models and the Safe are kept. The update is installed next to the old version and rolls back if the new one fails to start.",
      },
    ],
  },
  footer: {
    tagline: "Your intelligence — on your own hardware.",
    blurb: "A local AI for Windows. Free, no account needed.",
    cta: "Download for Windows",
    columns: [
      {
        title: "Product",
        links: [
          { href: "how-it-works", label: "How it works" },
          { href: "security", label: "Security" },
          { href: "principles", label: "Principles" },
        ],
      },
      {
        title: "Download",
        links: [
          { href: "download", label: "Download" },
          { href: "updates", label: "All versions" },
          { href: "documentation", label: "Docs" },
        ],
      },
    ],
    external: [
      { href: "https://github.com/MrPastio/monarch", label: "Source code" },
      { href: "https://github.com/MrPastio/monarch-releases/releases", label: "GitHub Releases" },
    ],
    honesty:
      "The update manifest is signed with Ed25519 and the installer is verified by SHA-256. The installer doesn’t have an Authenticode certificate yet, so Windows SmartScreen may show a warning.",
    rights: "Monarch · MrPastio",
  },
  ui: {
    oscar: "Oscar",
    jumpsLabel: "On this page",
    consentAsk: "Allow a one-time web search?",
    consentYes: "Allow",
    actionKeys: ["action", "source", "model"],
    kernelSteps: ["Check approval", "Execute", "Record the event"],
    receiptKeys: ["Request", "Action", "Decision", "Check"],
    agent: "agent",
    events: [
      { time: "02:14", text: "Startup items: no changes", tone: "ok" },
      { time: "02:16", text: "New file in Downloads checked", tone: "ok" },
      { time: "02:21", text: "Network connection: known process", tone: "ok" },
      { time: "02:30", text: "Attempt to change a scheduled task", tone: "warn" },
    ],
  },
  pages: {
    download: {
      title: "Download Monarch",
      lede: "The current version, how to verify the file, and a full archive of every release.",
      verifyTitle: "How to verify the file",
      verifySteps: [
        { title: "Download the installer", text: "With the button above or from the GitHub Release page — it’s the same file." },
        { title: "Compute SHA-256", text: "Open PowerShell in your Downloads folder and run:" },
        { title: "Compare", text: "The result must match the SHA-256 on this page character for character. If it doesn’t, don’t run the file." },
      ],
      command: "Get-FileHash .\\Monarch-Setup-0.2.5.0.exe -Algorithm SHA256",
      archiveTitle: "Version archive",
      archiveLede: "Every published installer. For everyday use we recommend the latest: older versions don’t receive fixes.",
      stateCurrent: "Current",
      stateArchive: "Archive",
      stateRevoked: "Revoked",
      stateHistory: "No installer",
      oldWarning: "This version doesn’t receive fixes. Unless you have a specific reason, download the current one.",
      revokedWarning: "This version was revoked from the update channel. It shouldn’t be installed for real work.",
      revokedAck: "I understand the risk and want to download a revoked version",
      historyNote: "This version shipped before the public channel — there’s no installer in the archive.",
      download: "Download",
      notes: "What’s new",
      sourceSnapshot: "GitHub is unavailable right now — showing a saved list of releases.",
    },
    updates: {
      title: "Monarch history",
      lede: "Every version — what changed and why. From the first Beta to today. Release notes are written in Russian.",
      future: {
        label: "In progress",
        title: "0.3 · Astra V3 and MAX",
        text: "A new agent core built on typed capabilities, the MAX cloud mode with 12 services, Gmail, GitHub and Calendar integrations. Not published yet.",
      },
      categories: { features: "Features", fixes: "Fixes", security: "Security", studio: "Studio" },
      open: "Details",
      published: "Published",
      withdrawnTitle: "Why it was revoked",
      supersededBy: "Replaced by",
      whatChanged: "What changed",
      howItWorks: "How to update",
      audience: "Who it matters to",
      allVersions: "All versions",
      filterAll: "All",
      filterLabel: "Show",
    },
    how: {
      kicker: "How it works",
      title: "How Monarch is built",
      lede: "Several separate processes, one rule-based core and dozens of modules. All of it on your computer.",
      jumps: [
        { href: "#processes", label: "Processes" },
        { href: "#route", label: "Request path" },
        { href: "#modules", label: "Modules" },
        { href: "#models", label: "Models and memory" },
      ],
      processTitle: "Five processes, each with its own job",
      processHint: "Pick a process — I’ll show what it talks to and where the boundary runs.",
      links: { ui: "commands and confirmations", model: "models and the agent", watch: "watches from the side", wall: "wall: the agent can’t pass" },
      processes: [
        { id: "window", title: "Monarch window", text: "The Electron interface. This is where you write, choose modes and confirm actions." },
        { id: "runtime", title: "Module runtime", text: "The Kernel and the modules. It listens only on 127.0.0.1 — nothing outside can reach it." },
        { id: "oscar", title: "Oscar", text: "The local backend: models, chat and the agent. Models run on llama.cpp in GGUF format." },
        { id: "safe", title: "Safe", text: "A separate process with no network. Nobody else ever sees the Safe’s keys." },
        { id: "security", title: "Security", text: "A Windows task with limited rights. It keeps working even when Monarch is closed." },
      ],
      kernelTitle: "One decision per action",
      kernelText: "Modules don’t grant themselves rights. They collect facts, and a single layer — the PolicyKernel — makes the final call: allow, ask you, or deny. Verification is separate: an action only counts as done once the core has confirmed its effect.",
      kernelFlow: ["Modules gather facts", "PolicyKernel decides", "The Kernel executes", "The result is checked"],
      modulesTitle: "21 modules in one system",
      modulesCount: "{n} of {total}",
      moduleFilters: [
        { id: "all", label: "All" },
        { id: "agent", label: "Agent" },
        { id: "data", label: "Data" },
        { id: "guard", label: "Protection" },
        { id: "link", label: "Connections" },
        { id: "system", label: "System" },
      ],
      modules: [
        { id: "oscar", group: "agent", name: "Oscar", text: "Chat and an agent that understands the task" },
        { id: "models", group: "data", name: "Models", text: "Local models and their installation" },
        { id: "memory", group: "data", name: "Memory", text: "Memory V4: remembers what matters, keeps projects apart" },
        { id: "coder", group: "agent", name: "Coder", text: "Working with code inside a chosen project" },
        { id: "computer", group: "agent", name: "Computer Use", text: "Sees windows, clicks, types — Beta" },
        { id: "system-shell", group: "agent", name: "Terminal", text: "Commands only within your permissions" },
        { id: "knowledge", group: "data", name: "Knowledge", text: "Search across your documents" },
        { id: "workspace", group: "data", name: "Workspaces", text: "The boundaries the agent works within" },
        { id: "artifacts", group: "data", name: "Artifacts", text: "Files and reports Monarch created" },
        { id: "astra", group: "agent", name: "Skills", text: "Ready-made scenarios via “+” or “$”" },
        { id: "voice", group: "link", name: "Voice", text: "Dictation and speech on the device" },
        { id: "profile", group: "data", name: "Profile", text: "Personality and conversation style" },
        { id: "safe", group: "guard", name: "Safe", text: "Encrypted storage" },
        { id: "security", group: "guard", name: "Security", text: "Monitoring and action protection" },
        { id: "sharing", group: "link", name: "Sharing", text: "Local access for your own programs" },
        { id: "telegram", group: "link", name: "Telegram", text: "A bot for talking to Monarch" },
        { id: "plugins", group: "agent", name: "Plugins", text: "Connectable services" },
        { id: "custom-tools", group: "agent", name: "Custom tools", text: "Tools you add yourself" },
        { id: "device", group: "system", name: "Device", text: "Hardware details for choosing a model" },
        { id: "diagnostics", group: "system", name: "Diagnostics", text: "Clear reasons for failures" },
        { id: "assistant", group: "system", name: "Assistant", text: "Basic answers and routing" },
      ],
      modelsTitle: "Models to choose from",
      modelsText: "Monarch offers Basic 2B, Basic 12B and Pro 27B and recommends the one that fits your computer. Models are downloaded separately from the app and stored on your drive.",
      memoryTitle: "Memory that doesn’t gossip",
      memoryText: "Memory V4 keeps ordinary chats apart from Coder projects, finds what’s useful from past conversations and marks answers where it used memory. You can turn it off; Incognito and sensitive sections never enter it.",
    },
    security: {
      kicker: "Security",
      title: "Trust you can verify",
      lede: "How Monarch decides what it may do, where the hard boundaries are, and what lies beyond them.",
      jumps: [
        { href: "#verdicts", label: "Decisions" },
        { href: "#access", label: "Access modes" },
        { href: "#protection", label: "Safe and Security" },
        { href: "#updates", label: "Updates" },
      ],
      verdictTitle: "Three possible decisions",
      verdicts: [
        { id: "allow", title: "Allow", text: "The action fits the chosen mode — Monarch executes it and verifies the result." },
        { id: "confirm", title: "Ask you", text: "A one-time confirmation bound to that exact action. If the action changes, a new one is needed." },
        { id: "deny", title: "Deny", text: "A hard stop. Neither confirmation nor owner rights can lift it." },
      ],
      updatesTitle: "Honest updates",
      updatesText: "The stable channel is signed with an Ed25519 key. Monarch checks the signature, size and SHA-256 of the installer before installing, puts the new version next to the old one and rolls back if it fails to start.",
      updateSteps: [
        { title: "Manifest", text: "The version list is signed with an Ed25519 key" },
        { title: "Check", text: "Signature, size and SHA-256 — before installing" },
        { title: "Side by side", text: "The new version installs next to the old one" },
        { title: "Rollback", text: "If it doesn’t start, the previous one comes back" },
      ],
      limitsTitle: "What lies beyond protection",
      limits: [
        "Malware already running under your account",
        "An administrator or a Windows kernel-level compromise",
        "A modified and rebuilt copy of Monarch",
        "Physical recovery of data from an SSD after deletion",
      ],
    },
    principles: {
      kicker: "Principles",
      title: "How Monarch is made",
      lede: "The rules Monarch is designed, written and tested by. They’re the same for people and for the AI agents that help build it.",
      designTitle: "Design",
      design: [
        { title: "Calm glass", text: "A minimal language: black, white, orange and yellow, moderate blur, nothing for effect’s sake." },
        { title: "Motion has weight", text: "Elements arrive and leave from a clear place, unfold and fold. No blinking, no constant glow." },
        { title: "One animation owner", text: "Any transition can be interrupted at any moment and never queues — the interface never makes you wait." },
        { title: "Respect for your settings", text: "If “reduce motion” is on in your system, Monarch and this site show final states without animation." },
      ],
      qualityTitle: "Quality",
      quality: [
        { title: "Compiling isn’t fixing", text: "A task is done when type checks, tests and a real scenario pass — not when the code builds." },
        { title: "Verify the result", text: "In the product and in development alike: an action isn’t done until its effect is confirmed." },
        { title: "Truth in the copy", text: "Every claim on this site is tied to code or a release. A test stops the site from promising “100%” or calling the installer signed while it isn’t." },
        { title: "Honest statuses", text: "Beta, Preview and Alpha are marked right in the interface. Unfinished work is never passed off as finished." },
      ],
      agentsTitle: "Built with AI agents",
      agentsText: "Monarch is developed together with several AI agents. Each has its own role and admission under an open policy: Codex and Claude as lead developers, Grok admitted as a worker, unknown agents not admitted. Each task is bound to a code version, allowed paths and a deadline; accepting the result is never automatic.",
      agentsRoster: [
        { name: "Codex", role: "lead developer", state: "lead" },
        { name: "Claude", role: "lead developer", state: "lead" },
        { name: "Grok", role: "admitted executor", state: "admitted" },
        { name: "Unknown agents", role: "not admitted", state: "denied" },
      ],
      motionTry: "Click — and interrupt it halfway",
      reducedOn: "Reduce motion is on for you right now — the site shows final states.",
      reducedOff: "Motion is on right now. Turn on reduce motion in your system and the site will show final states straight away.",
      layers: ["Paper", "Glass", "Night"],
      agentsSource: "The policy is described in SECURITY.md of the open repository",
      brandTitle: "The mark",
      brandText: "A shield with a crown and circuit traces: protection, sovereignty and computing on your own hardware. The primary version sits on a dark ground, the second on a light one.",
      brandDark: "Primary · dark ground",
      brandLight: "Secondary · light ground",
    },
    docs: {
      kicker: "Docs",
      title: "Getting started",
      lede: "Installation, first launch and answers to common questions — in plain words.",
      toc: "On this page",
      sections: [
        {
          id: "install",
          title: "Installation",
          steps: [
            "Download Monarch-Setup from this site or from GitHub Release.",
            "Run the installer. No administrator rights needed — Monarch installs for your account.",
            "If SmartScreen shows a warning, click “More info” → “Run anyway”. Check the SHA-256 first.",
          ],
        },
        {
          id: "first-run",
          title: "First launch",
          steps: [
            "Monarch suggests a model for your computer. You can pick several or skip the download.",
            "The download shows real progress and resumes after a restart.",
            "If automatic model installation fails, the window has step-by-step instructions with the exact files.",
          ],
        },
        {
          id: "permissions",
          title: "Permissions",
          steps: [
            "Choose an autonomy mode in settings: “Always ask”, “On its own in the project” or “On its own on the device”.",
            "Web search and cloud services ask for consent separately.",
            "Dangerous actions are always forbidden — that isn’t a setting.",
          ],
        },
        {
          id: "updates",
          title: "Updates",
          steps: [
            "Monarch checks the signed stable channel itself and offers a one-click update.",
            "Chats, settings, models and the Safe are kept.",
            "If the new version fails to start, Monarch returns to the previous one.",
          ],
        },
      ],
      troubleTitle: "If something goes wrong",
      trouble: [
        { q: "Edge blocks the download", a: "Use another browser or the GitHub Release page. Check the SHA-256 after downloading." },
        { q: "Answers are slow", a: "Pick a smaller model in settings. Pro 27B is noticeably slower than the Basic models and needs about 30 GB of memory." },
        { q: "Not enough disk space", a: "Models take gigabytes. You can remove them, or download them later in settings." },
      ],
    },
  },
};
